# Generated by Django 4.2.7 on 2023-12-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='empresas/fotos/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
