# Generated by Django 4.2.7 on 2023-12-12 03:16

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPat', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellidoMat', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('cedula', models.CharField(max_length=10)),
                ('carrera', models.CharField(choices=[('SOF', 'Ingeniería en Software'), ('BIO', 'Biotecnología'), ('IND', 'Ingeniería Industrial'), ('AMB', 'Ingeniería Ambiental'), ('ALI', 'Ingeniería de Alimentos'), ('MUL', 'Producción Audiovisual'), ('ADM', 'Administración de Empresas'), ('CON', 'Contabilidad y Auditoría'), ('TUR', 'Turismo'), ('COM', 'Comunicación'), ('ECO', 'Economía'), ('ENF', 'Enfermería'), ('NUT', 'Nutrición y Dietética'), ('FIS', 'Fisioterapia'), ('MED', 'Medicina'), ('PAD', 'Pedagogía de la Actividad Física y Deporte'), ('EDU', 'Educación'), ('PED', 'Pedagogía de los Idiomas Nacionales y Extranjeros'), ('EES', 'Educación Especial'), ('PLL', 'Pedagogía de la Lengua y Literatura')], max_length=3)),
                ('nivelEducativo', models.CharField(choices=[('BAC', 'Bachiller'), ('TER', 'Tercer Nivel'), ('POS', 'Posgrado')], max_length=3)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='estudiantes/fotos/')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ('apellidoPat',),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Postulaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateField()),
                ('estado', models.CharField(choices=[('POE', 'Postulación enviada'), ('APT', 'APTO'), ('NAP', 'NO APTO')], max_length=3)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('POS', 'Postulación'), ('CON', 'Contratación'), ('NOL', 'Nueva Oferta Laboral')], max_length=3)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('prioridad', models.CharField(choices=[('A', 'ALTA'), ('M', 'MEDIA'), ('B', 'BAJA')], max_length=1)),
                ('visto', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ('-fecha',),
            },
        ),
    ]
